### ISSUE TITLE
Flex wrap

### ISSUE THREAD

**Issue by mikebutts** [salahadem/Capstone_Colmar_Academy#2]
![image](https://user-images.githubusercontent.com/8017734/40974263-0331fd9a-6895-11e8-96e1-6311f0a66971.png)

What you could do , instead of using 2 rows, you can make 1 div with 6 divs inside with a width set to 30%. Then the containing div you put flex, and flex-wrap, then they will auto fill out.

**Comment by salahadem** [comment]
Yes, that is a great comment. I will try that.
