### ISSUE TITLE
 Last section

### ISSUE THREAD

**Issue by mikebutts** [salahadem/Capstone_Colmar_Academy#3]
![image](https://user-images.githubusercontent.com/8017734/40974340-47a1f174-6895-11e8-89d4-c77ba8fa39ad.png)

This is related to the DRY code, if you were to setup these divs the same as the first 2 sections, then make the video instead of the img tag, you would have similar looking sections.

**Comment by salahadem** [comment]
Yes, this is a very good comment. I did not think the one with video was similar. I will try that.
Thanks for the comment.
