### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mikebutts** [salahadem/Capstone_Colmar_Academy#4]
Meets expectations

Good job on this project it comes close to the spec. The code was neat and easy to read which is a major component in making websites. I left a couple issues for you to take a look out, they will improve the quality of code if not necessarily change the look of the site. Next, try to add a few more pages, maybe a form for sign in, some of the other pages, you can use w3schools.com for forms guide. unsplash.com or freepik.com for images and themeforest.com for web layout ideas. If you make this a full site you can add this as a great portfolio piece. Keep up the good work.

**Comment by salahadem** [comment]
thanks for you comment. This couse has been fun. I learned a lot from it.
Thanks for all the help you all provided.
